docker_start:
	docker-compose --env-file=.env.local -f docker-compose.yaml up -d

docker_stop:
	docker-compose --env-file=.env.local -f docker-compose.yaml stop

docker_restart:
	docker-compose --env-file=.env.local -f docker-compose.yaml restart
