POST http://localhost/api/v1/command/register_service
Content-Type: application/json

{
  "serviceId": "test_service",
  "url": "localhost"
}


curl -X POST --location "https://localhost/api/v1/command/service.register" \
    -H "Content-Type: application/json" \
    -d "{
          \"serviceId\": \"test_service\",
          \"url\": \"localhost\"
        }"