name: PHPUnit tests
on: push
env:
    # see https://github.com/composer/composer/issues/9368#issuecomment-718112361
    COMPOSER_ROOT_VERSION: "dev-main"
jobs:
  provide_packages_json:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: none

      - uses: "ramsey/composer-install@v1"

      # get package json list
      - id: output_data
        run: echo "::set-output name=matrix::$(vendor/bin/monorepo-builder packages-json)"

    outputs:
      matrix: ${{ steps.output_data.outputs.matrix }}
  # Label of the container job
  unit_tests:
    needs: provide_packages_json
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: ${{fromJson(needs.provide_packages_json.outputs.matrix)}}

    # Service containers to run with `unit_tests`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: docker.io/bitnami/postgresql:11-debian-10
        # Provide the password for postgres
        env:
          ALLOW_EMPTY_PASSWORD: yes
          
    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: none

      - name: Install Composer dependencies
        uses: "ramsey/composer-install@v1"

      - name: Run Unit Tests ${{ matrix.package }}
        run: vendor/bin/phpunit components/${{ matrix.package }}


